/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['div.gx-header-fixed[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    right: 0;\r\n    top: 57px;\r\n    padding-right:16px;\r\n    z-index: 1050;\r\n}\r\n\r\ndiv.gx-header-notfixed[_ngcontent-%COMP%] {\r\n    width:100%;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvaGVhZGVyL2hlYWRlci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2Rldi90ZXN0ZS9ncmF4YWltLWNvbW1vbnMvc3JjL2hlYWRlci9oZWFkZXIuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
