/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.drag-n-drop-container[_ngcontent-%COMP%] {\r\nwidth: 205px;\r\n    height: 56px;\r\n    border: 2px dashed gray;\r\n    border-radius: 5px;\r\n    padding: 14px 19px;\r\n    color: gray;\r\n    margin-top: 4px;\r\n    font-size: 1em;\r\n}\r\n\r\n.upload-button[_ngcontent-%COMP%]:hover {\r\n    cursor: pointer;\r\n}\r\n\r\n.upload-button[_ngcontent-%COMP%] {\r\n    color: #292b2c;\r\n    background-color: #e6e6e6;\r\n    background-image: none;\r\n    border-color: #adadad;\r\n    cursor: pointer;\r\n    padding: 0.30rem 1rem !important;\r\n    font-size: 1em;\r\n    border-radius: 0.2rem;\r\n    display: inline-block;\r\n    font-weight: normal;\r\n    line-height: 1.25;\r\n    text-align: center;\r\n    white-space: nowrap;\r\n    vertical-align: middle;\r\n    margin-bottom: 0px;\r\n    font-family: sans-serif;\r\n}\r\n\r\n.drag-n-drop-container[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\r\n    font-weight: bold;\r\n    display: block;\r\n    text-align: center;\r\n    text-transform: uppercase;\r\n    font-size: 1em;\r\n    color: gray;\r\n    margin: 10px;\r\n}\r\n\r\n.upload-button[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\r\n    display: none;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvZmlsZS11cGxvYWQvZmlsZS11cGxvYWQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy9maWxlLXVwbG9hZC9maWxlLXVwbG9hZC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
