/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.column-label[_ngcontent-%COMP%] {\r\n    margin-bottom: .1rem !important;\r\n}\r\n\r\n.data-table-header[_ngcontent-%COMP%] {\r\n    min-height: 25px;\r\n    margin-bottom: 5px;\r\n}\r\n.title[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    margin: 5px 0 0 5px;\r\n}\r\n.button-panel[_ngcontent-%COMP%] {\r\n    float: right;\r\n}\r\n.button-panel[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n    outline: none !important;\r\n}\r\n\r\n.column-selector-wrapper[_ngcontent-%COMP%] {\r\n    position: relative;\r\n}\r\n.column-selector-box[_ngcontent-%COMP%] {\r\n    box-shadow: 0 0 10px lightgray;\r\n    width: 200px;\r\n    padding: 10px;\r\n    position: absolute;\r\n    right: 0;\r\n    top: 1px;\r\n    z-index: 1060;\r\n}\r\n\r\n.column-selector-fixed-column[_ngcontent-%COMP%] {\r\n    font-style: italic;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvZGF0YXRhYmxlL2hlYWRlci9oZWFkZXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy9kYXRhdGFibGUvaGVhZGVyL2hlYWRlci5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
