/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './tooltip.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from './tooltip.component';
const styles_TooltipComponent:any[] = [import0.styles];
export const RenderType_TooltipComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_TooltipComponent,
  data: {}
}
);
function View_TooltipComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'span',[
      [
        'class',
        'text-danger ml-2'
      ]
      ,
      [
        'title',
        'Campo obrigatório'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['✱']))
  ]
  ,(null as any),(null as any));
}
function View_TooltipComponent_2(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'text-info font-weight-bold'
      ]
      ],[[
        8,
        'title',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['?']))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = import1.ɵinlineInterpolate(1,'',co.tip,'');
    ck(v,0,0,currVal_0);
  });
}
export function View_TooltipComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_TooltipComponent_1)),
    import1.ɵdid(8192,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),[' \n\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_TooltipComponent_2)),
    import1.ɵdid(8192,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['  \n  ']))
  ]
  ,(ck,v) => {
    var co:import3.TooltipComponent = v.component;
    const currVal_0:any = co.required;
    ck(v,2,0,currVal_0);
    const currVal_1:any = (co.tip.length > 0);
    ck(v,5,0,currVal_1);
  },(null as any));
}
function View_TooltipComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'gx-tooltip',([] as any[]),(null as any),(null as any),(null as any),View_TooltipComponent_0,RenderType_TooltipComponent)),
    import1.ɵdid(24576,(null as any),0,import3.TooltipComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TooltipComponentNgFactory:import1.ComponentFactory<import3.TooltipComponent> = import1.ɵccf('gx-tooltip',import3.TooltipComponent,View_TooltipComponent_Host_0,{
  tip: 'tip',
  required: 'required'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9vbHRpcC90b29sdGlwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy90b29sdGlwL3Rvb2x0aXAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9vbHRpcC90b29sdGlwLmNvbXBvbmVudC50cy5Ub29sdGlwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy90b29sdGlwL3Rvb2x0aXAuY29tcG9uZW50LnRzLlRvb2x0aXBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8c3BhbiB0aXRsZT1cIkNhbXBvIG9icmlnYXTDs3Jpb1wiIGNsYXNzPVwidGV4dC1kYW5nZXIgbWwtMlwiIFxuICAgICAgICAqbmdJZj1cInJlcXVpcmVkXCI+JiMxMDAzMzs8L3NwYW4+IFxuXG4gICAgPHNwYW4gdGl0bGU9XCJ7eyB0aXAgfX1cIiBjbGFzcz1cInRleHQtaW5mbyBmb250LXdlaWdodC1ib2xkXCIgXG4gICAgICAgICpuZ0lmPVwidGlwLmxlbmd0aCA+IDBcIj4/PC9zcGFuPiAgXG4gICIsIjxneC10b29sdGlwPjwvZ3gtdG9vbHRpcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNDSTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFDcUI7Ozs7OztNQUVyQjtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUMyQjs7OztJQURyQjtJQUFOLFNBQU0sU0FBTjs7Ozs7SUFKSjtJQUNJO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFDb0M7SUFFcEM7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUNtQzs7OztJQUgvQjtJQURKLFNBQ0ksU0FESjtJQUlJO0lBREosU0FDSSxTQURKOzs7OztJQ0pKO2dCQUFBOzs7Ozs7OzsifQ==
