/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from './toast.component';
const styles_ToastComponent:any[] = ([] as any[]);
export const RenderType_ToastComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ToastComponent,
  data: {}
}
);
function View_ToastComponent_2(l:any):import0.ɵViewDefinition {
      return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'close-button'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.close($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
function View_ToastComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),11,'div',[
      [
        'class',
        'toast alert'
      ]
      ,
      [
        'role',
        'alert'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(139264,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
    ,{
      klass: [
        0,
        'klass'
      ]
      ,
      ngClass: [
        1,
        'ngClass'
      ]

    }
    ,(null as any)),
    import0.ɵpad(1),
    (l()(),import0.ɵted((null as any),['\n            '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'span',[[
        'class',
        'toast-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'strong',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),[
      ' ',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_ToastComponent_2)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['            \n        ']))
  ]
  ,(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = 'toast alert';
    const currVal_1:any = ck(v,2,0,co.toast.type);
    ck(v,1,0,currVal_0,currVal_1);
    const currVal_4:any = co.toast.showClose;
    ck(v,10,0,currVal_4);
  },(ck,v) => {
    var co:any = v.component;
    const currVal_2:any = co.toast.alert;
    ck(v,6,0,currVal_2);
    const currVal_3:any = co.toast.msg;
    ck(v,7,0,currVal_3);
  });
}
export function View_ToastComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_ToastComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import2.ToastComponent = v.component;
    const currVal_0:any = co.toast.msg;
    ck(v,2,0,currVal_0);
  },(null as any));
}
function View_ToastComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'gx-toast',([] as any[]),(null as any),(null as any),(null as any),View_ToastComponent_0,RenderType_ToastComponent)),
    import0.ɵdid(24576,(null as any),0,import2.ToastComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ToastComponentNgFactory:import0.ComponentFactory<import2.ToastComponent> = import0.ɵccf('gx-toast',import2.ToastComponent,View_ToastComponent_Host_0,{toast: 'toast'},{closeToastEvent: 'closeToast'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9hc3R5L3RvYXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy90b2FzdHkvdG9hc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9hc3R5L3RvYXN0LmNvbXBvbmVudC50cy5Ub2FzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9hc3R5L3RvYXN0LmNvbXBvbmVudC50cy5Ub2FzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwidG9hc3QgYWxlcnRcIiBbbmdDbGFzc109XCJbdG9hc3QudHlwZV1cIiByb2xlPVwiYWxlcnRcIiAqbmdJZj1cInRvYXN0Lm1zZ1wiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0b2FzdC10ZXh0XCI+PHN0cm9uZz57e3RvYXN0LmFsZXJ0fX08L3N0cm9uZz4ge3t0b2FzdC5tc2d9fTwvc3Bhbj5cbiAgICAgICAgICAgIDxkaXYgKm5nSWY9XCJ0b2FzdC5zaG93Q2xvc2VcIiBjbGFzcz1cImNsb3NlLWJ1dHRvblwiIChjbGljayk9XCJjbG9zZSgkZXZlbnQpXCI+PC9kaXY+ICAgICAgICAgICAgXG4gICAgICAgIDwvZGl2PiIsIjxneC10b2FzdD48L2d4LXRvYXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkJDR1k7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUFrRDtRQUFBO1FBQUE7TUFBQTtNQUFsRDtFQUFBOzs7O0lBRko7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO2dCQUFBOzs7OztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO2dCQUF5QjtJQUF3RDtNQUM3RTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXlCO0lBQVE7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUF3QjtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQXFCO0lBQzlFO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBZ0Y7Ozs7SUFGL0U7SUFBb0I7SUFBekIsU0FBSyxVQUFvQixTQUF6QjtJQUVTO0lBQUwsVUFBSyxTQUFMOzs7SUFEaUM7SUFBQTtJQUF3QjtJQUFBOzs7OztJQUZyRTtJQUNRO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Ozs7SUFBK0Q7SUFBL0QsU0FBK0QsU0FBL0Q7Ozs7O0lDRFI7Z0JBQUE7Ozs7In0=
