/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['#toasty[_ngcontent-%COMP%] {\r\n  position: fixed;\r\n  z-index: 1100;\r\n  \r\n}\r\n#toasty[_ngcontent-%COMP%]   .close-button[_ngcontent-%COMP%]:focus {\r\n  outline: 0;\r\n}\r\n#toasty.toasty-position-top-left[_ngcontent-%COMP%] {\r\n  top: 12px;\r\n  left: 12px;\r\n}\r\n#toasty.toasty-position-top-right[_ngcontent-%COMP%] {\r\n  top: 12px;\r\n  right: 12px;\r\n}\r\n#toasty.toasty-position-bottom-right[_ngcontent-%COMP%] {\r\n  bottom: 12px;\r\n  right: 12px;\r\n}\r\n#toasty.toasty-position-bottom-left[_ngcontent-%COMP%] {\r\n  bottom: 12px;\r\n  left: 12px;\r\n}\r\n#toasty.toasty-position-top-center[_ngcontent-%COMP%] {\r\n  top: 68px;\r\n  left: 50%;\r\n  -webkit-transform: translate(-50%, 0%);\r\n          transform: translate(-50%, 0%);\r\n}\r\n#toasty.toasty-position-bottom-center[_ngcontent-%COMP%] {\r\n  bottom: 12px;\r\n  left: 50%;\r\n  -webkit-transform: translate(-50%, 0%);\r\n          transform: translate(-50%, 0%);\r\n}\r\n#toasty.toasty-position-center-center[_ngcontent-%COMP%] {\r\n  top: 50%;\r\n  left: 50%;\r\n  -webkit-transform: translate(-50%, 0%);\r\n          transform: translate(-50%, 0%);\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvdG9hc3R5L3RvYXN0eS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2Rldi90ZXN0ZS9ncmF4YWltLWNvbW1vbnMvc3JjL3RvYXN0eS90b2FzdHkuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
