/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './graxaim-commons.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'angular2-text-mask/dist/angular2TextMask';
import * as import5 from 'ng2-file-upload/file-upload/file-upload.module';
class GraxaimCommonsModuleInjector extends import0.ɵNgModuleInjector<import1.GraxaimCommonsModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _TextMaskModule_3:import4.TextMaskModule;
  _ReactiveFormsModule_4:import3.ReactiveFormsModule;
  _FileUploadModule_5:import5.FileUploadModule;
  _GraxaimCommonsModule_6:import1.GraxaimCommonsModule;
  __NgLocalization_7:import2.NgLocaleLocalization;
  __ɵi_8:import3.ɵi;
  __FormBuilder_9:import3.FormBuilder;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_7():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == null)) { (this.__NgLocalization_7 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _ɵi_8():import3.ɵi {
    if ((this.__ɵi_8 == null)) { (this.__ɵi_8 = new import3.ɵi()); }
    return this.__ɵi_8;
  }
  get _FormBuilder_9():import3.FormBuilder {
    if ((this.__FormBuilder_9 == null)) { (this.__FormBuilder_9 = new import3.FormBuilder()); }
    return this.__FormBuilder_9;
  }
  createInternal():import1.GraxaimCommonsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._TextMaskModule_3 = new import4.TextMaskModule();
    this._ReactiveFormsModule_4 = new import3.ReactiveFormsModule();
    this._FileUploadModule_5 = new import5.FileUploadModule();
    this._GraxaimCommonsModule_6 = new import1.GraxaimCommonsModule();
    return this._GraxaimCommonsModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.TextMaskModule)) { return this._TextMaskModule_3; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import5.FileUploadModule)) { return this._FileUploadModule_5; }
    if ((token === import1.GraxaimCommonsModule)) { return this._GraxaimCommonsModule_6; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import3.ɵi)) { return this._ɵi_8; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GraxaimCommonsModuleNgFactory:import0.NgModuleFactory<import1.GraxaimCommonsModule> = new import0.NgModuleFactory<any>(GraxaimCommonsModuleInjector,import1.GraxaimCommonsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvZ3JheGFpbS1jb21tb25zLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvdGVzdGUvZ3JheGFpbS1jb21tb25zL3NyYy9ncmF4YWltLWNvbW1vbnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
