/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.pagination-box[_ngcontent-%COMP%] {\r\n    margin-top: -5pt;\r\n    margin-bottom: 8px;\r\n}\r\n\r\n.pagination-ul[_ngcontent-%COMP%] {\r\n    margin: auto;\r\n}\r\n\r\nbutton.page-link[_ngcontent-%COMP%] {\r\n    cursor: pointer;\r\n}\r\n\r\nli.page-item.disabled[_ngcontent-%COMP%] {\r\n    cursor: not-allowed;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L3Rlc3RlL2dyYXhhaW0tY29tbW9ucy9zcmMvZGF0YXRhYmxlL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2Rldi90ZXN0ZS9ncmF4YWltLWNvbW1vbnMvc3JjL2RhdGF0YWJsZS9wYWdpbmF0aW9uL3BhZ2luYXRpb24uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
